### ISSUE TITLE
Is it possible to use WanaKana within a "contenteditable div", instead of an "input", or "textarea"?

### ISSUE THREAD

**Issue by escs98210** [WaniKani/WanaKana#104]
## Question

As the title says, can I bind WanaKana to a `<div contenteditable="true"></div>`, instead of an `<input>`, or a `<textarea>` element?

I would like the users to be able to style the text (bold, italic and underline). Hence, the preference for a contenteditable div.

**Comment by DJTB** [comment]
It might be possible, though I can envision a few potential problems occurring such as wanakana attempting to convert any markers within the div for styling. If you only bound to inner elements it might be okay (e.g. if a user sets italic, you move the binding to _within_ the styled element rather than the parent div which contains mixed content (text and styling markers). Depends how your text styling is handled I guess.

You could disable this early exit and give it a try.
https://github.com/WaniKani/WanaKana/blob/master/src/bind.js#L21

You could also ignore binding and handle the input conversion yourself with the methods provided, though you'll lose the benefits in the provided input handler (cursor repositioning etc).

**Comment by escs98210** [comment]
I'm sorry if it is a dumb question, (I am just a hobbyist programmer) but how do I "_disable that early exit_"?

I saved the code at https://unpkg.com/wanakana as a file called wanakana.js.
Next, I linked it to my .html by putting `<script src="wanakana.js"></script>` in the `head` of my .html document.
Then I opened the wanakana.js, looked for and deleted this part:
`if (!Xf.includes(t.nodeName)) throw Error("Element provided to Wanakana bind() was not a valid input or textarea element.\n Received: (" + JSON.stringify(t) + ")");`
But I still cannot use WanaKana inside a div. I guess I am doing this wrong...

**Comment by DJTB** [comment]
That was the right code to remove based on my suggestion.

Looking deeper though, I see we convert the text that is contained within an element's [value](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) - which is not a property that exists on plain elements like divs. We could possibly switch to [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent). 

Even if that was changed, you might still run into other issues using a plain element that is masquerading as an input. Although setting `contentEditable` does allow you to modify the contents of a div, and causes it to emit input events - it's still missing other aspects that come baked in with an input (for example composition events) which we rely on. TL;DR it becomes a pseudo-input, but not really.

This is probably outside the scope of the package's intent for real-time conversion, at least I don't personally have time to implement this at the moment.
 
You could go the other route of letting users enter their text, and only convert when they are finished / on submit.
You can use the [Wanakana methods](https://github.com/WaniKani/WanaKana#quick-reference) manually outside of `bind`.

```
const text = document.getElementById('wanakana-input').textContent;
const converted = wanakana.toHiragana(text);
// do what you want with converted text
```

**Comment by escs98210** [comment]
I understand. Thank you for all your help!
