### ISSUE TITLE
Adding @scottnicolson as a project collaborator

### ISSUE THREAD

**Issue by vietqhoang** [WaniKani/WanaKana#154]
Hi @mimshwright and @DJTB,

I want to open the discussion of adding @scottnicolson to the project team as a collaborator. He would act as a representative on our end (@tofugu). 

We recently have been active in our development which involves the integration of WanaKana. The work has surfaced some issues and things we would like to adjust. Some of this is already happening now with https://github.com/WaniKani/WanaKana/pull/153 and https://github.com/WaniKani/WanaKana/pull/151. I also think it’ll be positive to add another helping hand to assist in any goals this project has and process community submitted issues & PRs.

The main purpose is to shorten the feedback loop; working together to discuss these changes, how it fits with the goals of the project, and to get these changes out.

I am not super familiar at the moment with the current governance or working arrangement of the project. I (and @scottnicolson) want to respect what is in place if there is one well established. If there are any concerns please don’t hesitate to voice them.

I appreciate your involvement and views @mimshwright and @DJTB. I'll leave @scottnicolson to do their intros.

Mims, if you feel good about whats being proposed, you should have the necessary permissions to be able to add Scott to the project team. If not, I can do it.

**Comment by DJTB** [comment]
Completely fine with bringing Scott on board. 

There hasn't really been any specific governance, I've taken the helm by default since I was the only maintainer particularly active.

We'll also need to invite scott to the npm team for publishing permissions (you, myself, or mims can action this).

**Comment by scottnicolson** [comment]
@DJTB thanks for the support.  

- Is there a particular way that you would like to work together on changes? and are there changes that do need attention?
- When it comes to changes do we just review each others PRs? Do all PRs need to be reviewed?  
- Is there a guiding principle for what this project is and what it is not that will help determine whether changes should be made?  For example, there was talk about moving this project to typescript, was there a reason for this?  i.e. is the project considered feature complete is now just about fixing any issues? if so, is switching to typescript very high value for a project that is in maintenance mode?

Sorry for the barrage of questions, I haven't done much open source, and just trying to work out how the shared governance works for something like this.

**Comment by DJTB** [comment]
> @DJTB thanks for the support.
> 
> * Is there a particular way that you would like to work together on changes? and are there changes that do need attention?
> * When it comes to changes do we just review each others PRs? Do all PRs need to be reviewed?
> * Is there a guiding principle for what this project is and what it is not that will help determine whether changes should be made?  For example, there was talk about moving this project to typescript, was there a reason for this?  i.e. is the project considered feature complete is now just about fixing any issues? if so, is switching to typescript very high value for a project that is in maintenance mode?
> 

* I think it's fine to propose a feature/change in an issue if you want feedback, but if it's a bug fix feel free to go ahead and raise a PR without preamble.
* Review each others PRs - for the past five or so years it's basically been me alone so I've pushed changes through without reviews due to radio silence. I'm happy to review your PRs and have you review mine though.
* I think the guiding principle at this stage is to avoid adding unnecessary changes / overcomplicate further. Personally I think the project is faily feature complete for what it intends to provide. I think any major additions / diversions should probably be done in another package (e.g. if we chose to provide a Wanakana react component, it should be separate and use Wanakana as a peer-dep).
* Moving to Typescript I believe is considered a nice-to-have by @mimshwright and I. If this project was started today, that's how we'd go about it for ease of development / maintenance / consumption.

**Comment by scottnicolson** [comment]
> * Review each others PRs - for the past five or so years it's basically been me alone so I've pushed changes through without reviews due to radio silence. I'm happy to review your PRs and have you review mine though.

This works for me if you are happy with this too.

> * I think the guiding principle at this stage is to avoid adding unnecessary changes / overcomplicate further. Personally I think the project is faily feature complete for what it intends to provide. I think any major additions / diversions should probably be done in another package (e.g. if we chose to provide a Wanakana react component, it should be separate and use Wanakana as a peer-dep).

Sounds good.

> * Moving to Typescript I believe is considered a nice-to-have by @mimshwright and I. If this project was started today, that's how we'd go about it for ease of development / maintenance / consumption.

I agree if it was started today ..., my question was more about the how much value would be added if the project is in maintenance mode.  I wonder whether it would be considered a "major additions / diversion" at this point.  I am guessing though that due to time constraints of those involved that this particular issue parked for now.

---

In terms of bringing me on board, could you please add me to the NPM team and provide any roles I might need in GitHub?

**Comment by mimshwright** [comment]
Hi guys, 

I feel like a real grandpa to this project today and I'm so glad it remains relevant to people. 

I'm adding @scottnicolson to the project and I just made @DJTB an admin too. I think @DJTB might need to add you to NPM.

## Governance & Guiding Principles

First, I should say, for all practical purposes, I'm not really involved anymore. Whomever is willing to put in the work should get to make the big decisions AFAIAC. Duncan's suggestion sounds fine to me. 

The project was originally started as a commission by WaniKani / Tofugu. We made an agreement that I would develop it as an open source project that was sponsored by the company. The business needs of WaniKani are the major driver for all of the original features and are as good of a guiding directive as any. So I think giving them direct representation via Scott makes sense. 

## Typescript

The original code was written in CoffeeScript and later ported to ES6+ by @DJTB. 

I discussed porting it to TypeScript and even tried to do it but it was not as easy as I expected it to be and I lost motivation to finish. And to be totally honest, I was just kind of looking for something to keep busy during the pandemic. So we could consider that parked / abandoned. 

BTW, If I were to change anything at this point it would be 1. to separate the whole DOM binding functionality from the core library since it has historically been a source of issues and confusion and 2. to refactor some of the code to be more DRY. There are loads of functions that are essentially doing the same thing with minor tweaks and a functional-programming-oriented overhaul might make the code a lot tighter. But again, there is probably no real need for this since it's stable and not under active development. 

Welcome to the team!

**Comment by scottnicolson** [comment]
Thanks @mimshwright for sorting that and the guidance on where you would make changes.
