### ISSUE TITLE
Tokenize docs wrong

### ISSUE THREAD

**Issue by deelawn** [WaniKani/WanaKana#156]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/WaniKani/WanaKana/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

* [x] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [ ] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

A couple of tests on the tokenize documentation page are incorrect: https://wanakana.com/docs/global.html#tokenize

See the first two tests for the long mixed string. The `４` is in the wrong location in the input.
![image](https://github.com/WaniKani/WanaKana/assets/2497668/a521d050-72c6-4341-90cb-0b69d0ac4eba)

Is this generated? I couldn't find this docs page in this repo.

**Comment by vietqhoang** [comment]
Hi @deelawn.

I had to do a little digging since my involvement in the project isn't as high as the other contributors.

I did a project search for `漢字ひらがなカタ　カナ４` and found it in the comment below.

https://github.com/WaniKani/WanaKana/blob/a65c520afccf07352ef8f996504e6d5ff1822b13/src/tokenize.js#L65-L92

This leads me to believe the documentation is auto generated based on the comments.

It looks like the documentation is generated by [jsdoc](https://github.com/jsdoc/jsdoc) per my finding of the configuration file [jsdoc.json](https://github.com/WaniKani/WanaKana/blob/a65c520afccf07352ef8f996504e6d5ff1822b13/jsdoc.json) within the project.

Not related to the documentation, but here is the test for the `tokenize` function for your convenience: https://github.com/WaniKani/WanaKana/blob/a65c520afccf07352ef8f996504e6d5ff1822b13/test/core/tokenize.test.js

**Comment by DJTB** [comment]
You're correct. The docs are generated using the function comment decorations, and there is a mismatch between the comment and the test cases. I'm certain this was a mistake in copying the test cases to the documentation, so there's no cause for concern, other than the docs being misleading for this function.

I've made #157 to fix it.
