### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by franciscop** [WaniKani/WanaKana#53]
The latests version on NPM is the 1.3.7 while it seems the latest version here is the 1.3.11. Would you mind to release the latest version in NPM please?

It should be as easy as:

```
cd PROJECT_FOLDER
npm publish
```

Thank you!

PS, I'm using unpkg.com so the site breaks with the last `module.exports`, which doesn't appear on the current release: https://unpkg.com/wanakana@1.3.7/lib/wanakana.js

**Comment by mimshwright** [comment]
Interesting. I wasn't aware that we ever released it on npm. I'll see if it's possible for me to republish.

**Comment by mimshwright** [comment]
I am not authorized to update that package. Someone else has registered the package on NPM. I did ask to be added as a contributor but in the meantime, you can message the owner of the package.

**Comment by franciscop** [comment]
The people at NPM are great, so if you cannot solve it with the person who registered it for any reason you can just contact NPM and they will likely put you as the maintainer. I will contact the owner of the package though.

**Comment by DJTB** [comment]
For anyone interested, I forked this to add some extra methods, got fed up with the Coffeescript, started converting to modern JS, and got pretty carried away... long story short it's [on npm](https://www.npmjs.com/package/kanawana) and in UMD format so it should work fine with unpkg.

I extracted functions into modules to allow for individual imports of the utility functions (`import 'isHiragana'` etc), and thus much smaller build size in cases that don't involve conversion, fixed a bunch of old issues that were in this repo, added more extensive test cases, as well as a few extra methods/options I needed.

I didn't go for a PR since it turned out to be such a rewrite. Also I *did* modify the punctuation handling (which might have breaking changes for WaniKani etc).

**Comment by mimshwright** [comment]
@DJTB That's actually great news. I originally wrote it in Coffeescript because the project was spec'd as such, but having it in CS meant that I somewhat dread making changes to it 😭 . It's not totally clear whether I have the authority to make this call but I'd like to sunset the CS version into another branch and make an ES6 version the master. 

I'll take a look at yours.

**Comment by vietqhoang** [comment]
I am down with sunsetting the CS version for ES6.

**Comment by DJTB** [comment]
I'm easy, all the groundwork was by the original contributors ^^

I didn't remove any of the old tests, only added more - so theoretically I guess there shouldn't really be breaking changes, just unexpected benefits like `!` converting to `！` in the IME mode.

For reference, #45 and #46 are both integrated in the ES6 version.

**Comment by mimshwright** [comment]
Hey everyone, the owner of the NPM package has given me permission to publish the module. Only now, i have 3 problems.
1. I am having some issues with the code. I THINK it's working ok but the grunt-qunit task is not running due to an error on phantomjs. I haven't touched it in so long that I'm not confident in being able to build it anymore. Maybe someone can either build it and confirm that it's working or maybe I can publish then we check that it went ok? Or maybe we wait for point 2...
2. I want to move to the kanawana version asap. @DJTB I wonder if you want to make a pull request from your repo that could become Version 2.0. Is it as simple as that?
3. I have 0 time for this right now 😅

**Comment by DJTB** [comment]
Should be reasonably* straightforward.

Regarding NPM, I set up kanawana to be able to publish multiple packages (was thinking of providing IME mode separate to the convenience/text methods) - but it confuses the build system slightly, especially since it only is publishing a single package right now! I'll simplify that back to just publishing the main/single package. As well as a find/replace kanawana -> wanakana.

Once that's done, I could PR into a new branch here to do final cleanup: we'll need to reconnect / create WK links for [Travis](https://travis-ci.org/Kaniwani/KanaWana) & [Coveralls](https://coveralls.io/github/Kaniwani/KanaWana) at least. Close relevant issues & old PRs.

Would you like to make me a collaborator to assist with all this?

**Comment by vietqhoang** [comment]
I have sent the invite @DJTB. Let me or @mimshwright know if you need anything else.

**Comment by DJTB** [comment]
Started the conversion in [release-2.0](https://github.com/WaniKani/WanaKana/tree/release-2.0) branch.
Still in progress. Updated build & release scripts looking good so far.

Distribution files aren't committed - but the compiled browser package can still be copied during publish to the gh-pages branch for inclusion in demos/wanakana site.

@vietqhoang What do you want to do about docs?
* Just link to docs
* Just have basic usage
* Include basic usage in readme / on the Wanakana website **and** link from there to extended docs?

The docs are currently parsed with jsdoc [like so](https://kaniwani.github.io/KanaWana/docs/global.html)

**Comment by vietqhoang** [comment]
Thanks for the hard work. I think third option is the best?

**Comment by DJTB** [comment]
Naturally, but .

I was going to copy the current gh-pages branch to the master branch in a subdir - so it can then be pushed to gh-pages branch automatically with any updated changes from releases. However, the assets appear to have been built at some point - and I can't see how/where that was done. Is it from a separate repo? I can just hardcode the html changes if you won't want/need to rebuild the styles/js in future. Looking at gh-pages commits it seems the assets are effectively frozen as-is - and just the html is being updated for new versions.

Ideally it'd be nicer to keep the readme/site in sync since they contain approximately the same information - though if there is no longer any build for the website and changes are minimal enough (find and replace text in the html) it's probably quicker to just do it manually than to set up a new build.

**Comment by vietqhoang** [comment]
The pages and assets are all there is; no preprocessing is done.

Manual is fine, but if you want to streamline it go for it.

**Comment by DJTB** [comment]
Well, the assets include scss -> css but I won't change styling anyhow. Manual it is!

I've sent through a request to the WaniKani github org from travis and coveralls for authorization. @vietqhoang could you accept or prod someone else on the org to do so?

Should be ready to merge and publish once the CI passes and I've updated those links in the readme.

**Comment by vietqhoang** [comment]
Ahh was there SCSS? Been so long sincr I looked.

Missed the Travis request. Sorry. Just approved the rest of your requests.

**Comment by DJTB** [comment]
Aww dang. Think you'll have to log in to travis and flip the switch for me.

![image](https://user-images.githubusercontent.com/5353151/27255278-6c86c31c-539b-11e7-91d6-52af017dfb7b.png)

https://travis-ci.org/profile/WaniKani

**Comment by vietqhoang** [comment]
Switch is flipped

**Comment by DJTB** [comment]
@mimshwright @vietqhoang Do either of you want to pull down [release-2.0](https://github.com/WaniKani/WanaKana/tree/release-2.0), run `npm run build` and play with the dist files at all before I merge to master -> publish as 2.0.0?

#### After building:
`dist/*.*` files for direct/slim es6 imports
`dist/lib/wanakana.js` = main umd build
`dist/lib/wanakana.min.js` = minified umd build
`dist/lib/wanakana.esm.js` = es6 module build

When published, the npm package will reference the builds via `main`, `browser`, `module` fields so users can just require or import and they'll get the right one.

**Comment by vietqhoang** [comment]
Ran the build and took a look. Everything looks good to me. 👍 Thanks for the hard work.

**Comment by DJTB** [comment]
Right on! I'll publish it in the next day or so and deprecate kanawana -> point people to this package.

I'd love to take a stab at some of the remaining input issues sometime but there isn't a device lab hereabouts for me to test on. I doubt that emulation will provide valuable results, but I might see what browserstack can provide anyway. 

If any general new issues crop up from the release I should have the time to fix those.

**Comment by DJTB** [comment]
@mimshwright Can you add (or ask cuongcua90 to add) viet and I (or the entire WaniKani org?) as collaborators using [npm access](https://docs.npmjs.com/cli/access)? 

Otherwise if I try to publish I'm pretty sure it'll be rejected.

**Comment by mimshwright** [comment]
@DJTB I added you to WanaKana on NPM. You should be able to publish. If @vietqhoang  or anyone else wants to be added, please let me know your npm handle. 

Also, @DJTB I just noticed you're also in Berlin. Me too. How cool!

**Comment by DJTB** [comment]
Ah.. yes... well... あのーー... I was!
And will be again I suppose, I have some close friends there.

I've been moving about every 1-3 months for the past few years, so at any one time all my interweb accounts will say I'm in different countries. Causes trouble it does.

Perhaps I should make a script that can update all my damn accounts at once through `navigator.geolocation`. I'll even resort to programatically doing it with Nightmare.js if I have to haha.

**Comment by DJTB** [comment]
:tada: :balloon: :tada: 
Complete via 4e7b6ffff59ee6dccbf14250b9e902ba70cfb309

**Comment by vietqhoang** [comment]
@mimshwright My npm handle is viethoang. Thanks!

**Comment by quannt** [comment]
@vietqhoang @DJTB Seems like if I just do `import { isHiragana } from 'wanakana'`, the umd version of wanakana would be included, which means there's no tree shaking. 

This is because the default [target](https://webpack.js.org/concepts/targets/) of webpack is `'web'` and wanakana sets the default entry for browser to the umd version

```
  "main": "wanakana.js",
  "react-native": "wanakana.js",
  "module": "es/index.js",
  "browser": "umd/wanakana.min.js",
  "unpkg": "umd/wanakana.min.js"
```

I have to do `import { isHiragana } from 'wanakana/es'` instead to get the tree-shaking version.
