### ISSUE TITLE
Locking conversion to Hiragana or Katakana

### ISSUE THREAD

**Issue by floridagamer07** [WaniKani/WanaKana#57]
When using wanakana to bind an input I would like to suggest adding an option to lock conversion to hiragana or katakana. For now I have found a workaround by adding a custom eventListener and calling toKana(), feeding it text converted to upper/lower case.

**Comment by mimshwright** [comment]
Well, the IME mode is just for convenience and does pretty much the exact same thing as your workaround, that said, this would be an easy feature to add and sounds useful. 

Would you like to submit a pull request for this?

**Comment by DJTB** [comment]
Just a note - a quick look at the code shows that only `toKana` was really set up for dynamic input. Also, the `onInput` handler used in the IME mode does some extra cursor resets to ensure the input cursor is placed at the end of the altered input. 

Direct calls of `toHiragana` with a stream of input could miss some of the features - it's probably worth breaking out the IMEMode references to be handled in `toHiragana` and `toKatakana` rather than `toKana`.

I'll take a quick stab at this today and see what happens.

**Comment by DJTB** [comment]
@floridagamer07 Do you want to give https://github.com/WaniKani/WanaKana/blob/dev/gh-pages/assets/js/wanakana.min.js a shot and let me know if it's working as expected for you?

**Comment by floridagamer07** [comment]
Thanks for the quick response. I tried out the code and it works as expected, changing the option to toHiragana/toKatakana will lock the input conversion. Though one bug I found was when you bound an input with `wanakana.bind(input);` the 'n' block (なにぬねの) cannot be entered, it will show up as (ex. んあ), but binding an input with `wanakana.bind(input, { IMEMode: true });` everything works as expected and the 'n' block can be entered normally.

**Comment by DJTB** [comment]
Good catch! I've updated it now and everything seems groovy.
@mimshwright want me to go ahead and publish?

**Comment by mimshwright** [comment]
Sure. Go for it.

**Comment by DJTB** [comment]
Live on NPM.
