### ISSUE TITLE
Cursor goes to the end of input when converting the middle of text

### ISSUE THREAD

**Issue by seanblue** [WaniKani/WanaKana#61]
This may not be easy/possible to fix, but this case is relevant when fixing a typo. For example, you typed しなった, but meant to type しまった. Here are the steps to reproduce:

1. Type _sinatta_, which is converted to しなった. This results in the cursor being at the end of the input.
2. Move the cursor to before/after the な.
3. Delete the な. The cursor is now after the し.
4. Type _ma_, which is converted to ま, resulting in the full value in the input of しまった. However, this results in the cursor being at the end of the input. Ideally, the cursor would be immediately after the just-converted ま.

**Comment by DJTB** [comment]
This might be a `wontfix`.

We can set the cursor position after conversion since we know the keypress input length, which is often different to the converted characters. `kokonotsu` vs `九つ`. It might be difficult to guess what has been removed on a correction, especially if characters are selected and replaced. Inserting the cursor incorrectly is definitely less desired than *consistently* setting it to the end of input after a modification.

I'll take a look at it, but no promises.

**Comment by seanblue** [comment]
I figured that might be the case. It's pretty minor anyway.
