### ISSUE TITLE
String with long vowel(ー) and Hiragana does not work on toHiragana

### ISSUE THREAD

**Issue by nnishimura** [WaniKani/WanaKana#62]
```
wanakana.toHiragana('てすテスート'); // works
wanakana.toHiragana('てすート'); // TypeError!
wanakana.toHiragana('てすー戸'); // TypeError!
wanakana.toHiragana('手巣ート'); // TypeError!
wanakana.toHiragana('tesート'); // TypeError!
```

This seems to happen when the input is !Katakana + 'ー'
Gonna find a workaround on this, but they should work.

**Comment by DJTB** [comment]
Oh hey, good catch!

Some of these weren't really tested for since there aren't any valid long vowel continuations in your example inputs.

Regardless, we should still be passing through invalid ー markers  and converting as much as possible!
`てすート` => `てすーと`
`tesート` => `てsーと`

I've found the culprit and added your test cases.

**Comment by DJTB** [comment]
If you break anything else with weird combos feel free to create more issues! :sunglasses:
