### ISSUE TITLE
Underscore in katakana

### ISSUE THREAD

**Issue by Geggles** [WaniKani/WanaKana#68]
Is there a reason as to why `_` are not replaced by `ー` when converting from romaji to katakana? I mean sure, you may want to type an actual underscore, but the same reasoning applies to the minus sign. When using IME mode to convert romaji to katakana, you generally type everything in upper case, so a `-` becomes `_`. Before changing this in the code, I wanted to make sure that this is not intended behaviour.

EDIT: Used back ticks to escape and highlight markdown symbols

**Comment by DJTB** [comment]
##### Aside:
You'll want to enclose terms in backticks \` \` to write anything that can be interpreted as markdown. IE. underscores denote italics.

#### Short Answer:
The reasoning is to keep in line with normal IME conversion, in a sense of WYSIWYG.
Typing `ge-mu_.,<>()` in Google IME converts to `げーむ＿。、＜＞（）`
Similarly in katakana mode you will get `ゲーム＿。、＜＞（）`

#### Long Answer:
Using capitals with the IME does nothing, that's just a minor convenience feature with Wanakana since we don't provide a kana shift shortcut (maybe we could, though better left as an exercise for the developer to add a button that will then re-convert or set the input mode as hira or kata).

Originally there was no punctuation conversion, though I extended it to convert visually equivalent symbols for the more common instances like `、。（）［］` etc

I will admit, I took a liberty in deciding on smart quotes `‘’’` => `「」` and `“”` => `『』` whereas `[]` => `［］` rather than the normal IME equivalent of `[]` => `「」`. This was based on their actual usage in text IE: quotations so I was getting too clever for Wanakana here. It was nice to see `‘tasuketekure’tosakenda` converted to the Japanese equivalent of `「たすけてくれ」とさけんだ` (and converting nicely in reverse but I was probably pushing my luck with this approach :smile: 
This diverges from the WYSIWYG approach, so it's something I would be willing to change to be more in line with the original idea. It's not clear that to type `「` you need to enter `“` which most users aren't even aware is different to `'`. A better solution might be better to map `[]` to `「」` in toKana and `「」` to `“”` in toRomaji... but I digress.

As it stands, I don't see that `_` should convert to `ー` even if it's a hassle to disable caps / release shift. Is there something more I'm missing here, or it's just a question of typing in caps when converting?

**Comment by Geggles** [comment]
Alright, thank you for your thorough explanation, that does make a lot of sense. Maybe we could implement an API to customize the default behaviour, like an `update_mapping` function or something along those lines?

**Comment by DJTB** [comment]
Could potentially be added to options, and merged with the pre-defined mappings. 

I'm concerned that edge cases handled at different stages of `toKana` might end up different to what's expected with an updated mapping. I'm thinking of sequences along the lines of `kkou`, `nya`, `ltsu` and `n'`.

Not sure I can think of a specific example that would definitely go wrong, but since the actual 1 -> 1 map that we would be updating happens midway through `toKana` there's potential for things to get weird.
```
kanaChar = FROM_ROMAJI[chunkLC];
```

Perhaps not though, it's worth a shot and testing if it's feasible. If it's **just** updating punctuation/symbol mapping that is far safer and I don't think would run into issues.

**Comment by DJTB** [comment]
Alright so everything is now merged to dev, and I'm going to try to find some time and devices to manually test input with the dev branch :+1:

**Comment by DJTB** [comment]
FYI: after further thought I actually removed ヶヵ from toRomaji

The ヶ ヵ forms can be read as "ka, ga, or ko" in different situations and are effectively being used as symbols/kanji (and not as kana) when seen in 一ヶ月 etc. Therefore we should make no assumptions about converting them.

However, allowing the individual small forms to be entered specifically via (x|l)(ke|ka) in `toKana()` is still a valid use case roma -> kana and that functionality has been retained.

**Comment by DJTB** [comment]
You can `npm install wanakana@beta` if you want to easily try out your changes in a local project. I still want to do some more device testing before releasing normally.
