### ISSUE TITLE
japanese punctuation miss some character

### ISSUE THREAD

**Issue by halfsprit** [WaniKani/WanaKana#78]
"≪≫" ("\u226a\u226b") are missed in the constant.js export const FROM_ROMAJI

**Comment by DJTB** [comment]
≪≫ ("\u226a\u226b") are mathematical symbols (in English) and cannot be typed on a standard English keyboard so it doesn't make sense to convert toKana.

There are also the similar marks « » ("\u00ab\u00bb") for double quotes in French, German etc. but they aren't used in English, or on an English keyboard either.

Do you think ≪≫ should convert to 《》 or something else?

In the next major release (3.0.0) you will also be able to do this if you want anyway:
```
const options = { customKanaMapping: { '≪': '《', '≫': '》' };
toKana('≪romaji≫', options });
// => '《ろまじ》'
```

**Comment by DJTB** [comment]
Can you give an example where ≪≫ would be typed in English?

**Comment by halfsprit** [comment]
I've seen "≪≫“ many times in some Japanese website, so I think they should regard as Japanese punctuation char within isCharJapanesePunctuation.js。Maybe I'm wrong, because I'm a Chinese。

**Comment by DJTB** [comment]
Hmm, I think we'll keep the current behaviour unless a native speaker can confirm otherwise.

As far as I can tell from research, using ≪≫ in Japanese text is still incorrect (unless it is maths related) and this is a user/author mistake since ≪≫ are not actually the same as the Japanese punctuation marks 《》.

www.rikai.com/library/kanjitables/kanji_codes.unicode.shtml (not listed)
https://www.hadamitzky.de/english/lp_special_chars.htm (listed under すうがく = maths)

《 searching google in Japanese ~3.4 billion hits
≪ searching google in Japanese ~500 thousand hits

Current Wanakana:
`isJapanese('≪≫') // false`
`isJapanese('+-') // false`
`isJapanese('《》') // true`

**Comment by DJTB** [comment]
I'm not going to add these by default, but I'm going to add an extra param `allowed=[]` to the `is` functions since I need to use it internally anyway and then users can easily modify the behaviour like we will allow for custom mappings with the `to` functions.

In 3.0
```
 isJapanese('≪偽括弧≫');
 // => false
 isJapanese('≪偽括弧≫', ['≪', '≫']);
 // => true
```
