### ISSUE TITLE
String with Kanji not recognized as Japanese/only partial romajization

### ISSUE THREAD

**Issue by retorquere** [WaniKani/WanaKana#84]
When the input string is mixed Kanji/Hiragana/Katakana, it is not recognized as Japanese, and the transformation to Romaji leaves the Kanji characters:

```
var wanakana = require('wanakana');

console.log(wanakana.toRomaji('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！', { passRomaji: true }));
console.log(wanakana.isJapanese('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！'));
console.log(wanakana.isJapanese('泣き虫。！〜２￥ｚｅｎｋａｋｕ'))
```

outputs

```
感ji取retara手wo繋gou,重narunoha人生norain and remiria最高!
false
true
```

**Comment by DJTB** [comment]
```
console.log(wanakana.toRomaji('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！', { passRomaji: true }));
```
`passRomaji` is for use with converting to kana, it has no affect in toRomaji.
http://wanakana.com/docs/global.html#toHiragana

Kanji characters are not converted to romaji because their reading is contextual, which is outside the scope of Wanakana.

You can see an explanation and possible approaches to handle this here:
https://github.com/WaniKani/WanaKana/issues/81

```
console.log(wanakana.isJapanese('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！'));
```

This string has English in it (`and`) so it's not all Japanese. This _should_ result in false.

```
console.log(wanakana.isJapanese('泣き虫。！〜２￥ｚｅｎｋａｋｕ'))
```
This string has zenkaku (full-width latin characters) which we allow to pass since Japanese texts that reference English names are still in a Japanese format. IE: NHK news. Any normal latin characters will result in false as seen in the previous call with "and".

If it helps, compare normal English with zenkaku chars below:
`zenkaku`
`ｚｅｎｋａｋｕ`


Does this information help answer your questions?

**Comment by retorquere** [comment]
I get input where names are apparently commonly in Kanji. The solutions listed in #81 won't work for my context as they depend on external executables (I've added a comment to #81).

Thanks for the feedback in any case. I'll try to hack around kuroshiro.
